name: doksan
version: 0.0.1
author: Muhammed Ali Sit <sitmuhammedali@gmail.com>
description: A simple console application that enables hackers to get latest soccer scores and fixtures.
dependencies:
 http: any
 html: any
 args: any
