#!/usr/bin/env python

variables = {
	"tr": { 
		"_l_name":"https://www.scorespro.com/soccer/turkey/super-lig/",
		"_l_name_r":"https://www.scorespro.com/soccer/turkey/super-lig/results/",
		"_l_name_f":"https://www.scorespro.com/soccer/turkey/super-lig/fixtures/",
		"_l_name_t":"https://www.scorespro.com/soccer/turkey/super-lig/standings/",
		"trabzonspor":"https://www.scorespro.com/soccer/turkey/teams/trabzonspor-MTI5OTY=/",
		"besiktas":"https://www.scorespro.com/soccer/turkey/teams/besiktas-MjM1NDM=/",
		"basaksehir":"https://www.scorespro.com/soccer/turkey/teams/istanbul-bb-MjIxMTg=/",
		"galatasaray":"https://www.scorespro.com/soccer/turkey/teams/galatasaray-MjM1NTM=/",
		"fenerbahce":"https://www.scorespro.com/soccer/turkey/teams/fenerbahce-MTMwMjQ=/",
		"antalyaspor":"https://www.scorespro.com/soccer/turkey/teams/antalyaspor-MTMwMTk=/",
		"konyaspor":"https://www.scorespro.com/soccer/turkey/teams/konyaspor-MzEwOQ==/",
		"osmanlispor":"https://www.scorespro.com/soccer/turkey/teams/b-b-ankaraspor-MjEzNTc=/",
		"bursaspor":"https://www.scorespro.com/soccer/turkey/teams/bursaspor-MTI4MjI=/",
		"karabukspor":"https://www.scorespro.com/soccer/turkey/teams/kardemir-karabukspor-MjIyNzg=/",
		"genclerbirligi":"https://www.scorespro.com/soccer/turkey/teams/genclerbirligi-MTI5OTE=/",
		"kasimpasa":"https://www.scorespro.com/soccer/turkey/teams/kasimpasa-MjUwNzM=/",
		"akhisar":"https://www.scorespro.com/soccer/turkey/teams/akhisar-belediye-MzI4MDY=/",
		"alanyaspor":"https://www.scorespro.com/soccer/turkey/teams/alanyaspor-MjUwNzE=/",
		"kayserispor":"https://www.scorespro.com/soccer/turkey/teams/kayserispor-MTMwMTI=/",
		"yenimalatyaspor":"https://www.scorespro.com/soccer/turkey/teams/yeni-malatyaspor-MzI4MTc=/",
		"goztepe":"https://www.scorespro.com/soccer/turkey/teams/goztepe-MTI4ODM=/",
		"sivasspor":"https://www.scorespro.com/soccer/turkey/teams/sivasspor-MjIxMTM=/",
		"erzurumspor":"https://www.scorespro.com/soccer/turkey/teams/erzurum-bb-NDI2MTk=/",
		"hatayspor":"https://www.scorespro.com/soccer/turkey/teams/hatayspor-MzEwNzI=/",
		"fatihkaragumruk":"https://www.scorespro.com/soccer/turkey/teams/f-karagumruk-MjIxMjU=/"
	},
	"en": {
		"_l_name":"https://www.scorespro.com/soccer/england/premier-league/",
		"_l_name_r":"https://www.scorespro.com/soccer/england/premier-league/results/",
		"_l_name_f":"https://www.scorespro.com/soccer/england/premier-league/fixtures/",
		"_l_name_t":"https://www.scorespro.com/soccer/england/premier-league/standings/",
		"liverpool":"https://www.scorespro.com/soccer/england/teams/liverpool-fc-MTA5OTE=/",
		"everton":"https://www.scorespro.com/soccer/england/teams/everton-fc-MTA4MTg=/",
		"astonvilla":"https://www.scorespro.com/soccer/england/teams/aston-villa-NTI1OQ==/",
		"leicester":"https://www.scorespro.com/soccer/england/teams/leicester-city-MTA4MjI=/",
		"arsenal":"https://www.scorespro.com/soccer/england/teams/arsenal-fc-MTE1NzM=/",
		"tottenham":"https://www.scorespro.com/soccer/england/teams/tottenham-MjQzMg==/",
		"chelsea":"https://www.scorespro.com/soccer/england/teams/chelsea-fc-MjQyMA==/",
		"westham":"https://www.scorespro.com/soccer/england/teams/west-ham-MTA4MzA=/",
		"leeds":"https://www.scorespro.com/soccer/england/teams/leeds-united-NDY4Mw==/",
		"manchestercity":"https://www.scorespro.com/soccer/england/teams/manchester-city-MTE2NzY=/",
		"southampton":"https://www.scorespro.com/soccer/england/teams/southampton-NTI3Mw==/",
		"newcastle":"https://www.scorespro.com/soccer/england/teams/newcastle-united-MTA4MjY=/",
		"crystalpalace":"https://www.scorespro.com/soccer/england/teams/crystal-palace-MTA4Mzc=/",
		"manchesterunited":"https://www.scorespro.com/soccer/england/teams/manchester-united-MjQyNw==/",
		"wolves":"https://www.scorespro.com/soccer/england/teams/wolverhampton-wanderers-fc-MjQzMw==/",
		"brighton":"https://www.scorespro.com/soccer/england/teams/brighton-MjQ2Mg==/",
		"sheffield":"https://www.scorespro.com/soccer/england/teams/sheffield-united-MTA4NDc=/",
		"westbrom":"https://www.scorespro.com/soccer/england/teams/west-bromwich-MjQ1NA==/",
		"fulham":"https://www.scorespro.com/soccer/england/teams/fulham-fc-MjQyMg==/",
		"burnley":"https://www.scorespro.com/soccer/england/teams/burnley-fc-MTA4MzQ=/"
	}
}